name: "mysql_server"
services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOSTS: db
      PMA_PORT: 3306
    ports:
      - 8080:80
volumes:
  data:
