name: "mongodb_replica"
services:
  mongo:
    build: .
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: mongosh
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - config:/data/configdb
volumes:
  data:
  config:
